<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3Erdv4K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3Erdv4K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3Erdv4K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3Erdv4K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3Erdv4K\App_KernelDevDebugContainer([
    'container.build_hash' => '3Erdv4K',
    'container.build_id' => 'dde16e85',
    'container.build_time' => 1615131553,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3Erdv4K');
